### PR TITLE
Support new arabic character

### PR DESCRIPTION
**Pull request by HamedFathi**
Replace 'ة' with 'ه'

### CODE REVIEW

**Comment by jalalazimi** [comment]
Hi @HamedFathi, I added a bundler, please pull and use `npm run build` to create bundles.

**Comment by HamedFathi** [comment]
@jalalazimi Check it again, please.

**Review by jalalazimi — CHANGES_REQUESTED** [review]
Thanks @HamedFathi for updates, please remove `persian.min.js` and only keep the files that are generated by bundler. Also, revert the changes inside `package.json`.

**Comment by HamedFathi** [comment]
> Thanks @HamedFathi for updates, please remove `persian.min.js` and only keep the files that are generated by bundler. Also, revert the changes inside `package.json`.

Done!

**Pull request merged**
